Insert into SYSTEM.DOCTOR_DETAILS (DOCTORID,DOCTOR_CONTACT,DOCTOR_NAME,ROLE) values (11,1231231231,'Dr.Mohan','D');
Insert into SYSTEM.DOCTOR_DETAILS (DOCTORID,DOCTOR_CONTACT,DOCTOR_NAME,ROLE) values (12,9898989898,'Dr.Viki','D');

Insert into SYSTEM.APPOINTMENT_DETAILS (APPOINTMENT_ID,DOCTORID,PATIENTID,APP_DOC_COL,APP_LST_INDEX) values (10,30,20,11,0);
Insert into SYSTEM.APPOINTMENT_DETAILS (APPOINTMENT_ID,DOCTORID,PATIENTID,APP_DOC_COL,APP_LST_INDEX) values (11,31,21,11,1);
Insert into SYSTEM.APPOINTMENT_DETAILS (APPOINTMENT_ID,DOCTORID,PATIENTID,APP_DOC_COL,APP_LST_INDEX) values (12,32,22,11,2);
Insert into SYSTEM.APPOINTMENT_DETAILS (APPOINTMENT_ID,DOCTORID,PATIENTID,APP_DOC_COL,APP_LST_INDEX) values (90,90,90,null,null);
Insert into SYSTEM.APPOINTMENT_DETAILS (APPOINTMENT_ID,DOCTORID,PATIENTID,APP_DOC_COL,APP_LST_INDEX) values (98,12,98,12,0);
Insert into SYSTEM.APPOINTMENT_DETAILS (APPOINTMENT_ID,DOCTORID,PATIENTID,APP_DOC_COL,APP_LST_INDEX) values (99,12,99,12,1);
Insert into SYSTEM.APPOINTMENT_DETAILS (APPOINTMENT_ID,DOCTORID,PATIENTID,APP_DOC_COL,APP_LST_INDEX) values (97,12,97,12,2);

Insert into SYSTEM.PATIENT_DETAILS (PATIENT_ID,ADDRESS,AGE,CONTACT,PATIENT_NAME,WEIGHT,APP_DOC_COL,DOC_LST_INDEX,APPOINTMENTID,ROLE) values (23,'address1',11,1231231231,'patient 1',22,11,0,null,'P');
Insert into SYSTEM.PATIENT_DETAILS (PATIENT_ID,ADDRESS,AGE,CONTACT,PATIENT_NAME,WEIGHT,APP_DOC_COL,DOC_LST_INDEX,APPOINTMENTID,ROLE) values (24,'address2',11,1231231231,'patient 2',22,11,1,null,'P');
Insert into SYSTEM.PATIENT_DETAILS (PATIENT_ID,ADDRESS,AGE,CONTACT,PATIENT_NAME,WEIGHT,APP_DOC_COL,DOC_LST_INDEX,APPOINTMENTID,ROLE) values (25,'address3',11,1231231231,'patient 3',22,11,2,null,'P');
Insert into SYSTEM.PATIENT_DETAILS (PATIENT_ID,ADDRESS,AGE,CONTACT,PATIENT_NAME,WEIGHT,APP_DOC_COL,DOC_LST_INDEX,APPOINTMENTID,ROLE) values (26,'address4',11,1231231231,'patient 4',22,11,3,null,'P');
Insert into SYSTEM.PATIENT_DETAILS (PATIENT_ID,ADDRESS,AGE,CONTACT,PATIENT_NAME,WEIGHT,APP_DOC_COL,DOC_LST_INDEX,APPOINTMENTID,ROLE) values (97,'Niraj address1',11,1231231231,'Niraj',22,12,0,null,'P');
Insert into SYSTEM.PATIENT_DETAILS (PATIENT_ID,ADDRESS,AGE,CONTACT,PATIENT_NAME,WEIGHT,APP_DOC_COL,DOC_LST_INDEX,APPOINTMENTID,ROLE) values (98,'Morshi',12,9975244168,'Nikhil Wadatkar',12,12,3,null,'P');
Insert into SYSTEM.PATIENT_DETAILS (PATIENT_ID,ADDRESS,AGE,CONTACT,PATIENT_NAME,WEIGHT,APP_DOC_COL,DOC_LST_INDEX,APPOINTMENTID,ROLE) values (99,'kanha',76,10000000,'kanha',76,12,4,null,'P');
Insert into SYSTEM.PATIENT_DETAILS (PATIENT_ID,ADDRESS,AGE,CONTACT,PATIENT_NAME,WEIGHT,APP_DOC_COL,DOC_LST_INDEX,APPOINTMENTID,ROLE) values (11,'TEST',23,1212121212,'Neelima',23,11,5,null,'P');
Insert into SYSTEM.PATIENT_DETAILS (PATIENT_ID,ADDRESS,AGE,CONTACT,PATIENT_NAME,WEIGHT,APP_DOC_COL,DOC_LST_INDEX,APPOINTMENTID,ROLE) values (22,'TEST',23,1212121212,'Neelima',23,11,7,null,'P');
Insert into SYSTEM.PATIENT_DETAILS (PATIENT_ID,ADDRESS,AGE,CONTACT,PATIENT_NAME,WEIGHT,APP_DOC_COL,DOC_LST_INDEX,APPOINTMENTID,ROLE) values (33,'33',33,33,'ww',33,11,10,null,'P');
Insert into SYSTEM.PATIENT_DETAILS (PATIENT_ID,ADDRESS,AGE,CONTACT,PATIENT_NAME,WEIGHT,APP_DOC_COL,DOC_LST_INDEX,APPOINTMENTID,ROLE) values (44,'ww',33,33,'ww',33,11,11,null,'P');
Insert into SYSTEM.PATIENT_DETAILS (PATIENT_ID,ADDRESS,AGE,CONTACT,PATIENT_NAME,WEIGHT,APP_DOC_COL,DOC_LST_INDEX,APPOINTMENTID,ROLE) values (77,'hh',77,77,'hh',77,11,12,null,'P');
